In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
y = torch.tensor([2,1,3,4,2,2,3,6,8,9,10,11])
y.reshape(3,4)
y.numel()

12

In [7]:
(x==y).reshape(3,4)

tensor([[False,  True, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True]])

In [8]:
x.sum()

tensor(66)

In [9]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [10]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [11]:
before = id(x)
x+=y
id(x) == before,id(x),id(before)

(True, 2375386834544, 2375560920528)

NameError: name 'D' is not defined